openapi: 3.0.0
info:
  title: Product API
  description: API for managing products
  version: 1.0.0
paths:
  "/v1/products":
    get:
      summary: Get all products
      tags:
        - ProductsV1
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  elapsed_time:
                    type: string
                  data:
                    type: object
                    properties:
                      page_size:
                        type: integer
                      page_content:
                        type: array
                        items:
                          $ref: '#/components/schemas/Product'
    post:
      tags:
        - ProductsV1
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductWrite'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  elapsed_time:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "01HZ7E8GR7SBPV9F96XRR5HCW2"

  "/v1/products/{id}":
    get:
      tags:
        - ProductsV1
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  elapsed_time:
                    type: string
                  data:
                    type: object
                    properties:
                      product:
                        $ref: '#/components/schemas/Product'
    put:
      tags:
        - ProductsV1
      summary: Update a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductWrite'
      responses:
        '200':
          description: product updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  elapsed_time:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
    delete:
      tags:
        - ProductsV1
      summary: Delete a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: product deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  elapsed_time:
                    type: string

components:
  schemas:
    Product:
      type: object
      properties:
        product_id:
          type: string
          example: "01HZ7E8GR7SBPV9F96XRR5HCW2"
        name:
          type: string
          example: "Notebook"
        description:
          type: string
          example: "Notebook para os doencas do Fino"
        price:
          type: number
          fromat: float
          example: 2899.99
        quantity:
          type: number
          example: 10
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          nullable: true
    ProductWrite:
      type: object
      properties:
        name:
          type: string
          example: "Notebook"
        description:
          type: string
          example: "Notebook para os doencas do Fino"
        price:
          type: number
          fromat: float
          example: 2899.99
        quantity:
          type: number
          example: 10

