version: "3.7"
services:

  # Services
  of-customer-service:
    build: ../apis/customer-service/
    container_name: of-customer-service
    depends_on:
      - of-customer-postgres
      - of-customer-redis
    ports:
      - "8001:8001"
    environment:
      - DEGUG=true
    networks:
      - of-network

  of-product-service:
    build: ../apis/product-service/
    container_name: of-product-service
    depends_on:
      - of-product-postgres
    ports:
      - "8002:8002"
    environment:
      - DEGUG=true
    networks:
      - of-network

  of-order-service:
    build: ../apis/order-service/
    container_name: of-order-service
    depends_on:
      - of-order-mongo
    ports:
      - "8003:8003"
    environment:
      - DEGUG=true
    networks:
      - of-network

  # Databases
  of-customer-postgres:
    image: postgres
    container_name: of-customer-postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_DB=customer-service
      - POSTGRES_USER=customer
      - POSTGRES_PASSWORD=customer
    volumes:
      - ../apis/customer-service/db-schema/:/docker-entrypoint-initdb.d/
      - of_customer_postgres_vol:/var/lib/postgresql/data
    networks:
      - of-network

  of-product-postgres:
    image: postgres
    container_name: of-product-postgres
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_DB=product-service
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=product
    volumes:
      - ../apis/product-service/db-schema/:/docker-entrypoint-initdb.d/
      - of_product_postgres_vol:/var/lib/postgresql/data
    networks:
      - of-network

  of-order-mongo:
    image: mongo
    container_name: of-order-mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=order
      - MONGO_INITDB_ROOT_PASSWORD=order
    volumes:
      - of_order_mongo_vol:/data/db
    networks:
      - of-network

  # Cache
  of-customer-redis:
    image: redis
    container_name: of-customer-redis
    ports:
      - "6379:6380"
    networks:
      - of-network

  # Observability
  of-prometheus:
    image: prom/prometheus
    container_name: of-prometheus
    ports:
      - "9080:9090"
    volumes:
      - "./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "of_prometheus_vol:/prometheus"
    networks:
      - of-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  of-grafana:
    image: grafana/grafana
    container_name: of-grafana
    ports:
      - "3010:3000"
    volumes:
      - "./observability/grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards"
      - "of_grafana_vol:/var/lib/grafana/operation-fino"
    networks:
      - of-network

  # Profiling
  of-pyroscope:
    image: pyroscope/pyroscope:latest
    container_name: of-pyroscope
    ports:
      - "4040:4040"
    command: [ "server" ]
    networks:
      - of-network

volumes:
  of_customer_postgres_vol: {}
  of_product_postgres_vol: {}
  of_order_mongo_vol: {}
  of_prometheus_vol: {}
  of_grafana_vol: {}

networks:
  of-network:
    driver: bridge
    name: of-network
