version: "3.7"
services:

  of-customer-service:
    build: ../apis/customer-service/
    container_name: of-customer-service
    ports:
      - "8001:8001"
    environment:
      - DEGUG=true
    networks:
      - of-network

  of-customer-postgres:
    image: postgres
    container_name: of-customer-postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=customer
      - POSTGRES_PASSWORD=customer
      - POSTGRES_DB=customer-service
    volumes:
      - ../apis/customer-service/db-schema/:/docker-entrypoint-initdb.d/
      - of_customer_postgres_vol:/var/lib/postgresql/data
    networks:
      - of-network

  of-prometheus:
    image: prom/prometheus
    container_name: of-prometheus
    ports:
      - "9080:9090"
    volumes:
      - "./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "of_prometheus_vol:/prometheus/customer-service"
    networks:
      - of-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  of-grafana:
    image: grafana/grafana
    container_name: of-grafana
    ports:
      - "3010:3000"
    volumes:
      - "./observability/grafana/datasources:/etc/grafana/provisioning/datasources"
      - "./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards"
      - "of_grafana_vol:/var/lib/grafana/operation-fino"
    networks:
      - of-network

  of-pyroscope:
    image: pyroscope/pyroscope:latest
    container_name: of-pyroscope
    ports:
      - "4040:4040"
    command: [ "server" ]
    networks:
      - of-network

  of-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: of-elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    volumes:
      - of_elasticsearch_vol:/usr/share/elasticsearch/data
    networks:
      - of-network

  of-workshop-postgres:
    image: postgres
    container_name: of-workshop-postgres
    ports:
      - "5449:5432"
    environment:
      - POSTGRES_USER=workshop
      - POSTGRES_PASSWORD=workshop
      - POSTGRES_DB=workshop
    volumes:
      - of_workshop_postgres_vol:/var/lib/postgresql/data
    networks:
      - of-network

volumes:
  of_customer_postgres_vol: {}
  of_workshop_postgres_vol: {}
  of_elasticsearch_vol: {}
  of_prometheus_vol: {}
  of_grafana_vol: {}

networks:
  of-network:
    driver: bridge
    name: of-network
