// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	entity "cmd/customer-service/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CustomerCache is an autogenerated mock type for the CustomerCache type
type CustomerCache struct {
	mock.Mock
}

// ReadCacheByEmail provides a mock function with given fields: ctx, customerEmail
func (_m *CustomerCache) ReadCacheByEmail(ctx context.Context, customerEmail string) (*entity.Customer, error) {
	ret := _m.Called(ctx, customerEmail)

	if len(ret) == 0 {
		panic("no return value specified for ReadCacheByEmail")
	}

	var r0 *entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Customer, error)); ok {
		return rf(ctx, customerEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Customer); ok {
		r0 = rf(ctx, customerEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadCacheByID provides a mock function with given fields: ctx, customerID
func (_m *CustomerCache) ReadCacheByID(ctx context.Context, customerID string) (*entity.Customer, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for ReadCacheByID")
	}

	var r0 *entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Customer, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Customer); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadCacheByName provides a mock function with given fields: ctx, customerName
func (_m *CustomerCache) ReadCacheByName(ctx context.Context, customerName string) (*entity.Customer, error) {
	ret := _m.Called(ctx, customerName)

	if len(ret) == 0 {
		panic("no return value specified for ReadCacheByName")
	}

	var r0 *entity.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Customer, error)); ok {
		return rf(ctx, customerName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Customer); ok {
		r0 = rf(ctx, customerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteCacheByEmail provides a mock function with given fields: ctx, customer
func (_m *CustomerCache) WriteCacheByEmail(ctx context.Context, customer entity.Customer) error {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for WriteCacheByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Customer) error); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteCacheByID provides a mock function with given fields: ctx, customer
func (_m *CustomerCache) WriteCacheByID(ctx context.Context, customer entity.Customer) error {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for WriteCacheByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Customer) error); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteCacheByName provides a mock function with given fields: ctx, customer
func (_m *CustomerCache) WriteCacheByName(ctx context.Context, customer entity.Customer) error {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for WriteCacheByName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Customer) error); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomerCache creates a new instance of CustomerCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerCache {
	mock := &CustomerCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
