global:
  scrape_interval: "10s"
  evaluation_interval: "10s"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'of-customer-service'
    static_configs:
      - targets: ['of-prometheus:9090']
        labels:
          service: 'of-customer-service'
          instancee: 'of-customer-service-local'
