global:
  scrape_interval: "2s"
  evaluation_interval: "2s"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'of-customer-service'
    static_configs:
      - targets: [ 'of-customer-service:8001' ]
        labels:
          service: 'of-customer-service'
          instance: 'of-customer-service-local'

  - job_name: 'of-product-service'
    static_configs:
      - targets: [ 'of-product-service:8002' ]
        labels:
          service: 'of-product-service'
          instance: 'of-product-service-local'

  - job_name: 'of-order-service'
    static_configs:
      - targets: [ 'of-order-service:8003' ]
        labels:
          service: 'of-order-service'
          instance: 'of-order-service-local'
